version = 0.1

[default.deploy.parameters]
stack_name = "yt-transcribe-frontend"
resolve_s3 = true
s3_prefix = "yt-transcribe-frontend"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
