version = 0.1

[dev.deploy.parameters]
stack_name = "YT-transcribe-backend-dev"
resolve_s3 = true
s3_prefix = "YT-transcribe-backend-dev"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []

[default.deploy.parameters]
stack_name = "yt-transcribe-backend-dev"
resolve_s3 = true
s3_prefix = "yt-transcribe-backend-dev"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
