AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: YT-Transcribe Backend v1 - Decoupled video processing and transcription

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  AllowedOrigin:
    Type: String
    Default: '*'
    Description: Allowed CORS origin for API Gateway

Globals:
  Function:
    Runtime: python3.12
    Timeout: 900     # 15 minutes
    MemorySize: 1024
    Architectures:
      - x86_64
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        REGION: !Ref AWS::Region
    Tags:
      Project: YT-Transcribe
      Environment: !Ref Environment
      CostCenter: YouTubeProcessing
      Service: Lambda
      Owner: DevTeam
  Api:
    Cors:
      AllowMethods: "'POST, OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'http://yt-transcribe-frontend-dev-825765413106.s3-website.eu-west-2.amazonaws.com'"
      AllowCredentials: "'false'"

Resources:
  # API Gateway
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Name: !Sub yt-transcribe-api-${Environment}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true

  # Lambda layer for dependencies
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub yt-transcribe-dependencies-${Environment}
      Description: Dependencies for YT-Transcribe Lambda functions
      ContentUri: ../../backend/layer/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain

  # S3 bucket for storing audio files
  AudioBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub yt-transcribe-audio-${Environment}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldFiles
            Status: Enabled
            ExpirationInDays: 7
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Project
          Value: YT-Transcribe
        - Key: Environment
          Value: !Ref Environment
        - Key: CostCenter
          Value: YouTubeProcessing
        - Key: Service
          Value: S3
        - Key: Component
          Value: AudioStorage
        - Key: DataRetention
          Value: 7days

  # Lambda function for downloading videos
  DownloadVideoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../backend/download-video/
      Handler: app.lambda_handler
      Layers:
        - !Ref DependenciesLayer
      Environment:
        Variables:
          AUDIO_BUCKET: !Ref AudioBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref AudioBucket
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /download
            Method: POST
            RestApiId: !Ref Api
      Tags:
        Project: YT-Transcribe
        Environment: !Ref Environment
        CostCenter: YouTubeProcessing
        Service: Lambda
        Component: VideoDownloader
        Function: Download

  # Lambda function for transcribing audio
  TranscribeAudioFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../backend/transcribe-audio/
      Handler: app.lambda_handler
      Layers:
        - !Ref DependenciesLayer
      Environment:
        Variables:
          AUDIO_BUCKET: !Ref AudioBucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref AudioBucket
        - Statement:
            - Effect: Allow
              Action:
                - transcribe:StartTranscriptionJob
                - transcribe:GetTranscriptionJob
              Resource: '*'
      Tags:
        Project: YT-Transcribe
        Environment: !Ref Environment
        CostCenter: YouTubeProcessing
        Service: Lambda
        Component: AudioTranscriber
        Function: Transcribe

Outputs:
  AudioBucketName:
    Description: Name of the S3 bucket used for audio files
    Value: !Ref AudioBucket

  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/

  DownloadVideoFunctionArn:
    Description: ARN of the Download Video Lambda function
    Value: !GetAtt DownloadVideoFunction.Arn

  TranscribeAudioFunctionArn:
    Description: ARN of the Transcribe Audio Lambda function
    Value: !GetAtt TranscribeAudioFunction.Arn 